// backend/src/config/permissions.js

const PERMISSIONS = {
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  
  STOCK_VIEW: 'STOCK_VIEW',
  STOCK_CREATE: 'STOCK_CREATE',
  STOCK_EDIT: 'STOCK_EDIT',
  STOCK_DELETE: 'STOCK_DELETE',
  STOCK_IMPORT: 'STOCK_IMPORT',
  STOCK_EXPORT: 'STOCK_EXPORT',
  STOCK_LOCATION_MANAGE: 'STOCK_LOCATION_MANAGE',
  STOCK_MOVEMENT_MANAGE: 'STOCK_MOVEMENT_MANAGE',

  INTERVENTIONS_VIEW: 'INTERVENTIONS_VIEW',
  INTERVENTIONS_CREATE: 'INTERVENTIONS_CREATE',
  INTERVENTIONS_EDIT: 'INTERVENTIONS_EDIT',
  INTERVENTIONS_DELETE: 'INTERVENTIONS_DELETE',

  PREVENTIVE_VIEW: 'PREVENTIVE_VIEW',
  PREVENTIVE_CREATE: 'PREVENTIVE_CREATE',
  PREVENTIVE_EDIT: 'PREVENTIVE_EDIT',
  PREVENTIVE_DELETE: 'PREVENTIVE_DELETE',

  PLANIFICATION_VIEW: 'PLANIFICATION_VIEW',
  PLANIFICATION_CREATE: 'PLANIFICATION_CREATE',
  PLANIFICATION_EDIT: 'PLANIFICATION_EDIT',
  PLANIFICATION_DELETE: 'PLANIFICATION_DELETE',

  FORMATION_VIEW: 'FORMATION_VIEW',
  FORMATION_CREATE: 'FORMATION_CREATE',
  FORMATION_EDIT: 'FORMATION_EDIT',
  FORMATION_DELETE: 'FORMATION_DELETE',

  TECHNICIENS_VIEW: 'TECHNICIENS_VIEW',
  TECHNICIENS_CREATE: 'TECHNICIENS_CREATE',
  TECHNICIENS_EDIT: 'TECHNICIENS_EDIT',
  TECHNICIENS_DELETE: 'TECHNICIENS_DELETE',

  MACHINES_VIEW: 'MACHINES_VIEW',
  MACHINES_CREATE: 'MACHINES_CREATE',
  MACHINES_EDIT: 'MACHINES_EDIT',
  MACHINES_DELETE: 'MACHINES_DELETE',

  USERS_VIEW: 'USERS_VIEW',
  USERS_CREATE: 'USERS_CREATE',
  USERS_EDIT: 'USERS_EDIT',
  USERS_DELETE: 'USERS_DELETE'
};

const ROLE_PERMISSIONS = {
  ADMIN: Object.values(PERMISSIONS), // Full everywhere

  MANAGER: [
    PERMISSIONS.DASHBOARD_VIEW,
    // Stock View
    PERMISSIONS.STOCK_VIEW,
    // Interventions Full
    PERMISSIONS.INTERVENTIONS_VIEW, PERMISSIONS.INTERVENTIONS_CREATE, PERMISSIONS.INTERVENTIONS_EDIT, PERMISSIONS.INTERVENTIONS_DELETE,
    // Preventive Full
    PERMISSIONS.PREVENTIVE_VIEW, PERMISSIONS.PREVENTIVE_CREATE, PERMISSIONS.PREVENTIVE_EDIT, PERMISSIONS.PREVENTIVE_DELETE,
    // Planification Full
    PERMISSIONS.PLANIFICATION_VIEW, PERMISSIONS.PLANIFICATION_CREATE, PERMISSIONS.PLANIFICATION_EDIT, PERMISSIONS.PLANIFICATION_DELETE,
    // Formation Full
    PERMISSIONS.FORMATION_VIEW, PERMISSIONS.FORMATION_CREATE, PERMISSIONS.FORMATION_EDIT, PERMISSIONS.FORMATION_DELETE,
    // Techniciens View
    PERMISSIONS.TECHNICIENS_VIEW,
    // Machines View
    PERMISSIONS.MACHINES_VIEW,
    // Users View
    PERMISSIONS.USERS_VIEW
  ],

  GL: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.STOCK_VIEW,
    // Interventions Full
    PERMISSIONS.INTERVENTIONS_VIEW, PERMISSIONS.INTERVENTIONS_CREATE, PERMISSIONS.INTERVENTIONS_EDIT, PERMISSIONS.INTERVENTIONS_DELETE,
    // Preventive Full
    PERMISSIONS.PREVENTIVE_VIEW, PERMISSIONS.PREVENTIVE_CREATE, PERMISSIONS.PREVENTIVE_EDIT, PERMISSIONS.PREVENTIVE_DELETE,
    // Planification Full
    PERMISSIONS.PLANIFICATION_VIEW, PERMISSIONS.PLANIFICATION_CREATE, PERMISSIONS.PLANIFICATION_EDIT, PERMISSIONS.PLANIFICATION_DELETE,
    // Formation Full
    PERMISSIONS.FORMATION_VIEW, PERMISSIONS.FORMATION_CREATE, PERMISSIONS.FORMATION_EDIT, PERMISSIONS.FORMATION_DELETE,
    // Techniciens Full
    PERMISSIONS.TECHNICIENS_VIEW, PERMISSIONS.TECHNICIENS_CREATE, PERMISSIONS.TECHNICIENS_EDIT, PERMISSIONS.TECHNICIENS_DELETE,
    PERMISSIONS.MACHINES_VIEW
  ],

  TL: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.STOCK_VIEW,
    // Interventions Full
    PERMISSIONS.INTERVENTIONS_VIEW, PERMISSIONS.INTERVENTIONS_CREATE, PERMISSIONS.INTERVENTIONS_EDIT, PERMISSIONS.INTERVENTIONS_DELETE,
    // Preventive Full
    PERMISSIONS.PREVENTIVE_VIEW, PERMISSIONS.PREVENTIVE_CREATE, PERMISSIONS.PREVENTIVE_EDIT, PERMISSIONS.PREVENTIVE_DELETE,
    // Planification Full
    PERMISSIONS.PLANIFICATION_VIEW, PERMISSIONS.PLANIFICATION_CREATE, PERMISSIONS.PLANIFICATION_EDIT, PERMISSIONS.PLANIFICATION_DELETE,
    PERMISSIONS.FORMATION_VIEW,
    PERMISSIONS.TECHNICIENS_VIEW,
    PERMISSIONS.MACHINES_VIEW
  ],

  SUPERVISEUR: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.STOCK_VIEW,
    // Interventions Full
    PERMISSIONS.INTERVENTIONS_VIEW, PERMISSIONS.INTERVENTIONS_CREATE, PERMISSIONS.INTERVENTIONS_EDIT, PERMISSIONS.INTERVENTIONS_DELETE,
    // Preventive Full
    PERMISSIONS.PREVENTIVE_VIEW, PERMISSIONS.PREVENTIVE_CREATE, PERMISSIONS.PREVENTIVE_EDIT, PERMISSIONS.PREVENTIVE_DELETE,
    PERMISSIONS.PLANIFICATION_VIEW,
    PERMISSIONS.FORMATION_VIEW,
    PERMISSIONS.TECHNICIENS_VIEW,
    PERMISSIONS.MACHINES_VIEW
  ],

  DESIGNER: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.INTERVENTIONS_VIEW,
    // Planification Full
    PERMISSIONS.PLANIFICATION_VIEW, PERMISSIONS.PLANIFICATION_CREATE, PERMISSIONS.PLANIFICATION_EDIT, PERMISSIONS.PLANIFICATION_DELETE,
    PERMISSIONS.FORMATION_VIEW,
    PERMISSIONS.MACHINES_VIEW
  ],

  TECHNICIEN: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.STOCK_VIEW,
    // Interventions Full
    PERMISSIONS.INTERVENTIONS_VIEW, PERMISSIONS.INTERVENTIONS_CREATE, PERMISSIONS.INTERVENTIONS_EDIT, PERMISSIONS.INTERVENTIONS_DELETE,
    PERMISSIONS.PREVENTIVE_VIEW,
    PERMISSIONS.PLANIFICATION_VIEW,
    PERMISSIONS.FORMATION_VIEW,
    // Techniciens: Own/Team means they can view
    PERMISSIONS.TECHNICIENS_VIEW,
    PERMISSIONS.MACHINES_VIEW
  ],

  TECHNICIENSTOCK: [
    PERMISSIONS.DASHBOARD_VIEW,
    // Stock Full
    PERMISSIONS.STOCK_VIEW, PERMISSIONS.STOCK_CREATE, PERMISSIONS.STOCK_EDIT, PERMISSIONS.STOCK_DELETE,
    PERMISSIONS.STOCK_IMPORT, PERMISSIONS.STOCK_EXPORT, PERMISSIONS.STOCK_LOCATION_MANAGE, PERMISSIONS.STOCK_MOVEMENT_MANAGE,
    PERMISSIONS.MACHINES_VIEW
  ],

  OPERATEUR: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.STOCK_VIEW,
    PERMISSIONS.INTERVENTIONS_VIEW,
    PERMISSIONS.PLANIFICATION_VIEW,
    PERMISSIONS.FORMATION_VIEW,
    PERMISSIONS.MACHINES_VIEW
  ]
};

const hasPermission = (role, permission) => {
  if (!ROLE_PERMISSIONS[role]) return false;
  return ROLE_PERMISSIONS[role].includes(permission);
};

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission
};
